name: clean_architecture_test
description: Clean Architecture Implementation

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-287.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  shared_preferences: ^2.0.15
  data_connection_checker:
    path: packages/data_connection_checker
  http: ^0.13.5
  bloc: ^8.1.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  mockito: ^5.3.2
  mocktail: ^0.3.0
  very_good_analysis: ^5.1.0

flutter:

  uses-material-design: true

  assets:
    - test/fixtures/































